/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/cart`; params?: Router.UnknownInputParams; } | { pathname: `/cart/CartItem`; params?: Router.UnknownInputParams; } | { pathname: `/products/ProductCard`; params?: Router.UnknownInputParams; } | { pathname: `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/order/OrderItem`; params?: Router.UnknownInputParams; } | { pathname: `/order`; params?: Router.UnknownInputParams; } | { pathname: `/payment`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/products/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/cart`; params?: Router.UnknownOutputParams; } | { pathname: `/cart/CartItem`; params?: Router.UnknownOutputParams; } | { pathname: `/products/ProductCard`; params?: Router.UnknownOutputParams; } | { pathname: `/forgot-password`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/order/OrderItem`; params?: Router.UnknownOutputParams; } | { pathname: `/order`; params?: Router.UnknownOutputParams; } | { pathname: `/payment`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/products/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/cart${`?${string}` | `#${string}` | ''}` | `/cart/CartItem${`?${string}` | `#${string}` | ''}` | `/products/ProductCard${`?${string}` | `#${string}` | ''}` | `/forgot-password${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/order/OrderItem${`?${string}` | `#${string}` | ''}` | `/order${`?${string}` | `#${string}` | ''}` | `/payment${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/cart`; params?: Router.UnknownInputParams; } | { pathname: `/cart/CartItem`; params?: Router.UnknownInputParams; } | { pathname: `/products/ProductCard`; params?: Router.UnknownInputParams; } | { pathname: `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/order/OrderItem`; params?: Router.UnknownInputParams; } | { pathname: `/order`; params?: Router.UnknownInputParams; } | { pathname: `/payment`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `/products/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/products/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
